.TH "_xmlNs" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlNs \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_xmlNs\fP * \fBnext\fP"
.br
.ti -1c
.RI "xmlNsType \fBtype\fP"
.br
.ti -1c
.RI "const xmlChar * \fBhref\fP"
.br
.ti -1c
.RI "const xmlChar * \fBprefix\fP"
.br
.ti -1c
.RI "void * \fB_private\fP"
.br
.ti -1c
.RI "struct \fB_xmlDoc\fP * \fBcontext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 348 of file tree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
