.TH "_xmlDOMWrapCtxt" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlDOMWrapCtxt \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tree\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_private\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "void * \fBnamespaceMap\fP"
.br
.ti -1c
.RI "xmlDOMWrapAcquireNsFunction \fBgetNsForNodeFunc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
xmlDOMWrapCtxt:
.PP
Context for DOM wrapper-operations\&. 
.PP
Definition at line 551 of file tree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
