.TH "_xmlParserNodeInfoSeq" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlParserNodeInfoSeq \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBmaximum\fP"
.br
.ti -1c
.RI "unsigned long \fBlength\fP"
.br
.ti -1c
.RI "\fBxmlParserNodeInfo\fP * \fBbuffer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 100 of file parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
