.TH "_xmlID" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlID \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_xmlID\fP * \fBnext\fP"
.br
.ti -1c
.RI "const xmlChar * \fBvalue\fP"
.br
.ti -1c
.RI "\fBxmlAttrPtr\fP \fBattr\fP"
.br
.ti -1c
.RI "const xmlChar * \fBname\fP"
.br
.ti -1c
.RI "int \fBlineno\fP"
.br
.ti -1c
.RI "struct \fB_xmlDoc\fP * \fBdoc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 416 of file tree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
