.TH "_xmlAttr" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlAttr \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_private\fP"
.br
.ti -1c
.RI "xmlElementType \fBtype\fP"
.br
.ti -1c
.RI "const xmlChar * \fBname\fP"
.br
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBchildren\fP"
.br
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBlast\fP"
.br
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fB_xmlAttr\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fB_xmlAttr\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fB_xmlDoc\fP * \fBdoc\fP"
.br
.ti -1c
.RI "\fBxmlNs\fP * \fBns\fP"
.br
.ti -1c
.RI "xmlAttributeType \fBatype\fP"
.br
.ti -1c
.RI "void * \fBpsvi\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 393 of file tree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
