.TH "_xmlNotation" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlNotation \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const xmlChar * \fBname\fP"
.br
.ti -1c
.RI "const xmlChar * \fBPublicID\fP"
.br
.ti -1c
.RI "const xmlChar * \fBSystemID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 153 of file tree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
