.TH "_xmlSAXHandler" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlSAXHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "internalSubsetSAXFunc \fBinternalSubset\fP"
.br
.ti -1c
.RI "isStandaloneSAXFunc \fBisStandalone\fP"
.br
.ti -1c
.RI "hasInternalSubsetSAXFunc \fBhasInternalSubset\fP"
.br
.ti -1c
.RI "hasExternalSubsetSAXFunc \fBhasExternalSubset\fP"
.br
.ti -1c
.RI "resolveEntitySAXFunc \fBresolveEntity\fP"
.br
.ti -1c
.RI "getEntitySAXFunc \fBgetEntity\fP"
.br
.ti -1c
.RI "entityDeclSAXFunc \fBentityDecl\fP"
.br
.ti -1c
.RI "notationDeclSAXFunc \fBnotationDecl\fP"
.br
.ti -1c
.RI "attributeDeclSAXFunc \fBattributeDecl\fP"
.br
.ti -1c
.RI "elementDeclSAXFunc \fBelementDecl\fP"
.br
.ti -1c
.RI "unparsedEntityDeclSAXFunc \fBunparsedEntityDecl\fP"
.br
.ti -1c
.RI "setDocumentLocatorSAXFunc \fBsetDocumentLocator\fP"
.br
.ti -1c
.RI "startDocumentSAXFunc \fBstartDocument\fP"
.br
.ti -1c
.RI "endDocumentSAXFunc \fBendDocument\fP"
.br
.ti -1c
.RI "startElementSAXFunc \fBstartElement\fP"
.br
.ti -1c
.RI "endElementSAXFunc \fBendElement\fP"
.br
.ti -1c
.RI "referenceSAXFunc \fBreference\fP"
.br
.ti -1c
.RI "charactersSAXFunc \fBcharacters\fP"
.br
.ti -1c
.RI "ignorableWhitespaceSAXFunc \fBignorableWhitespace\fP"
.br
.ti -1c
.RI "processingInstructionSAXFunc \fBprocessingInstruction\fP"
.br
.ti -1c
.RI "commentSAXFunc \fBcomment\fP"
.br
.ti -1c
.RI "warningSAXFunc \fBwarning\fP"
.br
.ti -1c
.RI "errorSAXFunc \fBerror\fP"
.br
.ti -1c
.RI "fatalErrorSAXFunc \fBfatalError\fP"
.br
.ti -1c
.RI "getParameterEntitySAXFunc \fBgetParameterEntity\fP"
.br
.ti -1c
.RI "cdataBlockSAXFunc \fBcdataBlock\fP"
.br
.ti -1c
.RI "externalSubsetSAXFunc \fBexternalSubset\fP"
.br
.ti -1c
.RI "unsigned int \fBinitialized\fP"
.br
.ti -1c
.RI "void * \fB_private\fP"
.br
.ti -1c
.RI "startElementNsSAX2Func \fBstartElementNs\fP"
.br
.ti -1c
.RI "endElementNsSAX2Func \fBendElementNs\fP"
.br
.ti -1c
.RI "xmlStructuredErrorFunc \fBserror\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 705 of file parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
