.TH "_xmlDtd" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlDtd \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fB_private\fP"
.br
.ti -1c
.RI "xmlElementType \fBtype\fP"
.br
.ti -1c
.RI "const xmlChar * \fBname\fP"
.br
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBchildren\fP"
.br
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBlast\fP"
.br
.ti -1c
.RI "struct \fB_xmlDoc\fP * \fBparent\fP"
.br
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBprev\fP"
.br
.ti -1c
.RI "struct \fB_xmlDoc\fP * \fBdoc\fP"
.br
.ti -1c
.RI "void * \fBnotations\fP"
.br
.ti -1c
.RI "void * \fBelements\fP"
.br
.ti -1c
.RI "void * \fBattributes\fP"
.br
.ti -1c
.RI "void * \fBentities\fP"
.br
.ti -1c
.RI "const xmlChar * \fBExternalID\fP"
.br
.ti -1c
.RI "const xmlChar * \fBSystemID\fP"
.br
.ti -1c
.RI "void * \fBpentities\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 365 of file tree\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
