.TH "_xmlParserNodeInfo" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlParserNodeInfo \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fB_xmlNode\fP * \fBnode\fP"
.br
.ti -1c
.RI "unsigned long \fBbegin_pos\fP"
.br
.ti -1c
.RI "unsigned long \fBbegin_line\fP"
.br
.ti -1c
.RI "unsigned long \fBend_pos\fP"
.br
.ti -1c
.RI "unsigned long \fBend_line\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file parser\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
