.TH "_xmlError" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlError \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBdomain\fP"
.br
.ti -1c
.RI "int \fBcode\fP"
.br
.ti -1c
.RI "char * \fBmessage\fP"
.br
.ti -1c
.RI "xmlErrorLevel \fBlevel\fP"
.br
.ti -1c
.RI "char * \fBfile\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.ti -1c
.RI "char * \fBstr1\fP"
.br
.ti -1c
.RI "char * \fBstr2\fP"
.br
.ti -1c
.RI "char * \fBstr3\fP"
.br
.ti -1c
.RI "int \fBint1\fP"
.br
.ti -1c
.RI "int \fBint2\fP"
.br
.ti -1c
.RI "void * \fBctxt\fP"
.br
.ti -1c
.RI "void * \fBnode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 75 of file xmlerror\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
