.TH "_xmlGlobalState" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlGlobalState \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBxmlParserVersion\fP"
.br
.ti -1c
.RI "\fBxmlSAXLocator\fP \fBxmlDefaultSAXLocator\fP"
.br
.ti -1c
.RI "\fBxmlSAXHandlerV1\fP \fBxmlDefaultSAXHandler\fP"
.br
.ti -1c
.RI "\fBxmlSAXHandlerV1\fP \fBdocbDefaultSAXHandler\fP"
.br
.ti -1c
.RI "\fBxmlSAXHandlerV1\fP \fBhtmlDefaultSAXHandler\fP"
.br
.ti -1c
.RI "xmlFreeFunc \fBxmlFree\fP"
.br
.ti -1c
.RI "xmlMallocFunc \fBxmlMalloc\fP"
.br
.ti -1c
.RI "xmlStrdupFunc \fBxmlMemStrdup\fP"
.br
.ti -1c
.RI "xmlReallocFunc \fBxmlRealloc\fP"
.br
.ti -1c
.RI "xmlGenericErrorFunc \fBxmlGenericError\fP"
.br
.ti -1c
.RI "xmlStructuredErrorFunc \fBxmlStructuredError\fP"
.br
.ti -1c
.RI "void * \fBxmlGenericErrorContext\fP"
.br
.ti -1c
.RI "int \fBoldXMLWDcompatibility\fP"
.br
.ti -1c
.RI "xmlBufferAllocationScheme \fBxmlBufferAllocScheme\fP"
.br
.ti -1c
.RI "int \fBxmlDefaultBufferSize\fP"
.br
.ti -1c
.RI "int \fBxmlSubstituteEntitiesDefaultValue\fP"
.br
.ti -1c
.RI "int \fBxmlDoValidityCheckingDefaultValue\fP"
.br
.ti -1c
.RI "int \fBxmlGetWarningsDefaultValue\fP"
.br
.ti -1c
.RI "int \fBxmlKeepBlanksDefaultValue\fP"
.br
.ti -1c
.RI "int \fBxmlLineNumbersDefaultValue\fP"
.br
.ti -1c
.RI "int \fBxmlLoadExtDtdDefaultValue\fP"
.br
.ti -1c
.RI "int \fBxmlParserDebugEntities\fP"
.br
.ti -1c
.RI "int \fBxmlPedanticParserDefaultValue\fP"
.br
.ti -1c
.RI "int \fBxmlSaveNoEmptyTags\fP"
.br
.ti -1c
.RI "int \fBxmlIndentTreeOutput\fP"
.br
.ti -1c
.RI "const char * \fBxmlTreeIndentString\fP"
.br
.ti -1c
.RI "xmlRegisterNodeFunc \fBxmlRegisterNodeDefaultValue\fP"
.br
.ti -1c
.RI "xmlDeregisterNodeFunc \fBxmlDeregisterNodeDefaultValue\fP"
.br
.ti -1c
.RI "xmlMallocFunc \fBxmlMallocAtomic\fP"
.br
.ti -1c
.RI "\fBxmlError\fP \fBxmlLastError\fP"
.br
.ti -1c
.RI "xmlParserInputBufferCreateFilenameFunc \fBxmlParserInputBufferCreateFilenameValue\fP"
.br
.ti -1c
.RI "xmlOutputBufferCreateFilenameFunc \fBxmlOutputBufferCreateFilenameValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 81 of file globals\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
