.TH "_xmlParserInputBuffer" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlParserInputBuffer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBcontext\fP"
.br
.ti -1c
.RI "xmlInputReadCallback \fBreadcallback\fP"
.br
.ti -1c
.RI "xmlInputCloseCallback \fBclosecallback\fP"
.br
.ti -1c
.RI "\fBxmlCharEncodingHandlerPtr\fP \fBencoder\fP"
.br
.ti -1c
.RI "\fBxmlBufferPtr\fP \fBbuffer\fP"
.br
.ti -1c
.RI "\fBxmlBufferPtr\fP \fBraw\fP"
.br
.ti -1c
.RI "int \fBcompressed\fP"
.br
.ti -1c
.RI "int \fBerror\fP"
.br
.ti -1c
.RI "unsigned long \fBrawconsumed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 125 of file xmlIO\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
