.TH "_xmlCharEncodingHandler" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlCharEncodingHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "xmlCharEncodingInputFunc \fBinput\fP"
.br
.ti -1c
.RI "xmlCharEncodingOutputFunc \fBoutput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 131 of file encoding\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
