.TH "_xmlChSRange" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_xmlChSRange \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned short \fBlow\fP"
.br
.ti -1c
.RI "unsigned short \fBhigh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file chvalid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
