.TH "impvar" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
impvar \- The Implicit Variable 
The implicit variable in LOLCODE is denoted by the keyword \fCIT\fP and stores a copy of the result of the most recently evaluated expression statement, that is, an expression all by itself on a line\&. (See http://lolcode.com/specs/1.2#conditionals for an example\&.) 
