.TH "NSArray(RegexKitAdditions)" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSArray(RegexKitAdditions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(NSArray *) - \fBarrayByMatchingObjectsWithRegex:\fP"
.br
.ti -1c
.RI "(NSArray *) - \fBarrayByMatchingObjectsWithRegex:inRange:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBcontainsObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBcontainsObjectMatchingRegex:inRange:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBcountOfObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBcountOfObjectsMatchingRegex:inRange:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBindexOfObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBindexOfObjectMatchingRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSIndexSet *) - \fBindexSetOfObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(NSIndexSet *) - \fBindexSetOfObjectsMatchingRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSArray *) - \fBarrayByMatchingObjectsWithRegex:\fP"
.br
.ti -1c
.RI "(NSArray *) - \fBarrayByMatchingObjectsWithRegex:inRange:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBcontainsObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBcontainsObjectMatchingRegex:inRange:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBcountOfObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBcountOfObjectsMatchingRegex:inRange:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBindexOfObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBindexOfObjectMatchingRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSIndexSet *) - \fBindexSetOfObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(NSIndexSet *) - \fBindexSetOfObjectsMatchingRegex:inRange:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file NSArray\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
