.TH "NSData(RegexKitAdditions)" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSData(RegexKitAdditions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:inRange:capture:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSData *) - \fBsubdataByMatching:\fP"
.br
.ti -1c
.RI "(NSData *) - \fBsubdataByMatching:inRange:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:inRange:capture:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSData *) - \fBsubdataByMatching:\fP"
.br
.ti -1c
.RI "(NSData *) - \fBsubdataByMatching:inRange:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file NSData\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
