.TH "NSMutableSet(RegexKitAdditions)" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSMutableSet(RegexKitAdditions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(void) - \fBremoveObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(void) - \fBaddObjectsFromArray:matchingRegex:\fP"
.br
.ti -1c
.RI "(void) - \fBaddObjectsFromSet:matchingRegex:\fP"
.br
.ti -1c
.RI "(void) - \fBremoveObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(void) - \fBaddObjectsFromArray:matchingRegex:\fP"
.br
.ti -1c
.RI "(void) - \fBaddObjectsFromSet:matchingRegex:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 59 of file NSSet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
