.TH "NSMutableString(RegexKitAdditions)" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSMutableString(RegexKitAdditions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(RKUInteger) - \fBmatch:replace:withString:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:inRange:replace:withString:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:replace:withFormat:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:inRange:replace:withFormat:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:inRange:replace:withFormat:arguments:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:replace:withString:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:inRange:replace:withString:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:replace:withFormat:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:inRange:replace:withFormat:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBmatch:inRange:replace:withFormat:arguments:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 85 of file NSString\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
