.TH "NSObject(RegexKitAdditions)" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSObject(RegexKitAdditions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInArray:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInArray:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBfirstMatchingRegexInArray:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInArray:library:options:error:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInArray:library:options:error:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBfirstMatchingRegexInArray:library:options:error:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInSet:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInSet:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInSet:library:options:error:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInSet:library:options:error:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInArray:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInArray:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBfirstMatchingRegexInArray:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInArray:library:options:error:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInArray:library:options:error:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBfirstMatchingRegexInArray:library:options:error:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInSet:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInSet:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByAnyRegexInSet:library:options:error:\fP"
.br
.ti -1c
.RI "(\fBRKRegex\fP *) - \fBanyMatchingRegexInSet:library:options:error:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file NSObject\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
