.TH "NSSet(RegexKitAdditions)" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSSet(RegexKitAdditions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(id) - \fBanyObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBcontainsObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBcountOfObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(NSSet *) - \fBsetByMatchingObjectsWithRegex:\fP"
.br
.ti -1c
.RI "(id) - \fBanyObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBcontainsObjectMatchingRegex:\fP"
.br
.ti -1c
.RI "(RKUInteger) - \fBcountOfObjectsMatchingRegex:\fP"
.br
.ti -1c
.RI "(NSSet *) - \fBsetByMatchingObjectsWithRegex:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file NSSet\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
