.TH "NSString(RegexKitAdditions)" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NSString(RegexKitAdditions) \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "(BOOL) - \fBgetCapturesWithRegexAndReferences:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBgetCapturesWithRegex:inRange:references:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:inRange:capture:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:inRange:\fP"
.br
.ti -1c
.RI "(\fBRKEnumerator\fP *) - \fBmatchEnumeratorWithRegex:\fP"
.br
.ti -1c
.RI "(\fBRKEnumerator\fP *) - \fBmatchEnumeratorWithRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:withReferenceFormat:arguments:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:replace:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:replace:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:replace:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:replace:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:replace:withReferenceFormat:arguments:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBgetCapturesWithRegexAndReferences:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBgetCapturesWithRegex:inRange:references:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange *) - \fBrangesOfRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:\fP"
.br
.ti -1c
.RI "(NSRange) - \fBrangeOfRegex:inRange:capture:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:\fP"
.br
.ti -1c
.RI "(BOOL) - \fBisMatchedByRegex:inRange:\fP"
.br
.ti -1c
.RI "(\fBRKEnumerator\fP *) - \fBmatchEnumeratorWithRegex:\fP"
.br
.ti -1c
.RI "(\fBRKEnumerator\fP *) - \fBmatchEnumeratorWithRegex:inRange:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:withReferenceFormat:arguments:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:replace:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:replace:withReferenceString:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:replace:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:replace:withReferenceFormat:\fP"
.br
.ti -1c
.RI "(NSString *) - \fBstringByMatching:inRange:replace:withReferenceFormat:arguments:\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 52 of file NSString\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
