.TH "pcre_callout_block" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcre_callout_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBversion\fP"
.br
.ti -1c
.RI "int \fBcallout_number\fP"
.br
.ti -1c
.RI "int * \fBoffset_vector\fP"
.br
.ti -1c
.RI "PCRE_SPTR \fBsubject\fP"
.br
.ti -1c
.RI "int \fBsubject_length\fP"
.br
.ti -1c
.RI "int \fBstart_match\fP"
.br
.ti -1c
.RI "int \fBcurrent_position\fP"
.br
.ti -1c
.RI "int \fBcapture_top\fP"
.br
.ti -1c
.RI "int \fBcapture_last\fP"
.br
.ti -1c
.RI "void * \fBcallout_data\fP"
.br
.ti -1c
.RI "int \fBpattern_position\fP"
.br
.ti -1c
.RI "int \fBnext_item_length\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 227 of file pcre\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
