.TH "pcre_extra" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcre_extra \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long int \fBflags\fP"
.br
.ti -1c
.RI "void * \fBstudy_data\fP"
.br
.ti -1c
.RI "unsigned long int \fBmatch_limit\fP"
.br
.ti -1c
.RI "void * \fBcallout_data\fP"
.br
.ti -1c
.RI "const unsigned char * \fBtables\fP"
.br
.ti -1c
.RI "unsigned long int \fBmatch_limit_recursion\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 213 of file pcre\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
