.TH "TokenData" 3 "Tue May 8 2012" "ResKnife" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TokenData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tokenizer\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "float \fBf\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores the data associated with a \fBToken\fP structure\&. 
.PP
Definition at line 161 of file tokenizer\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float \fBTokenData::f\fP"
Floating point data\&. 
.PP
Definition at line 163 of file tokenizer\&.h\&.
.SS "int \fBTokenData::i\fP"
Integer data\&. 
.PP
Definition at line 162 of file tokenizer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ResKnife from the source code\&.
